### ISSUE TITLE
[Question] Border highlighting and hiding lua line

### ISSUE THREAD

**Issue by ajitid** [shortcuts/no-neck-pain.nvim#104]
Ref. https://old.reddit.com/r/vimplugins/comments/zxndcz/update_noneckpainnvim_dead_simple_plugin_to/j24owce/

![image](https://user-images.githubusercontent.com/26769888/210018621-d1830908-d522-4014-bffb-9e0e9ee67f81.png)

Few things here:
1. The border at right appears correctly (is grey, takes in `WinSeparator` as highlight) but the left one is white, which probably infers it from `Normal`
2. I just updated nvim to latest nightly and `:NoNeckPain` is unable to hide statusline anymore. I'm using [lualine](https://github.com/nvim-lualine/lualine.nvim).

For 1, I'd prefer it to use `WinSeparator` too. For 2, I have no idea what caused this.

**Comment by ajitid** [comment]
To solve 2, a manual integration is required it seems: https://github.com/Pocco81/true-zen.nvim/issues/91

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue!

> The border at right appears correctly (is grey, takes in WinSeparator as highlight) but the left one is white, which probably infers it from Normal

Looking at the showcase (https://github.com/shortcuts/no-neck-pain.nvim/wiki/Showcase), it seems that I don't have the white line with my theme. Do you experience the same thing when opening a normal vsplit without the plugin enabled?

> I just updated nvim to latest nightly and :NoNeckPain is unable to hide statusline anymore. I'm using [lualine](https://github.com/nvim-lualine/lualine.nvim).

Was it ever before? I never intentionally did it, but I'm usually using a global status line so I might have missed it. I'll definitely investigate!

**Comment by ajitid** [comment]
> Do you experience the same thing when opening a normal vsplit without the plugin enabled?

No I don't.

**Comment by shortcuts** [comment]
> > Do you experience the same thing when opening a normal vsplit without the plugin enabled?
> 
> No I don't.

Oops that a bug then, I'll investigate asap! What's your theme name so I can try to reproduce?

I believe a group is missing here https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/util/color.lua#L170

**Comment by ajitid** [comment]
I'm using https://github.com/kvrohit/rasmus.nvim

**Comment by shortcuts** [comment]
hey @ajitid, It seems correct on my side, do you have custom configuration for either the theme or no-neck-pain?

<img width="1280" alt="Screenshot 2022-12-30 at 16 24 26" src="https://user-images.githubusercontent.com/20689156/210086343-09b91455-0aed-4256-92d0-32c8093d1148.png">

**Comment by ajitid** [comment]
Yeah, my bad `let g:rasmus_transparent = 1` was causing this.

**Comment by shortcuts** [comment]
> Yeah, my bad. `let g:rasmus_transparent = 1` was causing this. That border issue is now gone
> 
> ![image](https://user-images.githubusercontent.com/26769888/210086709-4dfc60e8-e16d-4eb7-8d12-fc4e72bd6f57.png)

Ok make sense! I believe I can close the issue then :D

**Comment by shortcuts** [comment]
opened a new discussion here https://github.com/shortcuts/no-neck-pain.nvim/issues/494
