### ISSUE TITLE
mkview triggers error when exiting the plugin

### ISSUE THREAD

**Issue by pelegs** [shortcuts/no-neck-pain.nvim#112]
# Description

When exiting a file while NoNeckPain is toggled, the following error occurs:

    Error executing vim.schedule lua callback: ...er/start/no-neck-pain.nvim/lua/no-neck-pain/util/win.lua:122
    : Vim(mkview):E32: No file name
    stack traceback:
            [C]: in function 'nvim_win_close'
            ...er/start/no-neck-pain.nvim/lua/no-neck-pain/util/win.lua:122: in function 'close'
            ...packer/start/no-neck-pain.nvim/lua/no-neck-pain/main.lua:57: in function 'close'
            ...packer/start/no-neck-pain.nvim/lua/no-neck-pain/main.lua:350: in function <
            ...packer/start/no-neck-pain.nvim/lua/no-neck-pain/main.lua:325>

## Steps to reproduce

1. Open a file
2. Toggle NoNeckPain on (`:NoNeckPain`)
3. Quit neovim

## Expected behavior

The error should not appear.

## Environment

- Neovim version: 0.8.2, Release (LuaJIT 2.1.0-beta3)
- no-neck-pain.nvim version: 0.2.3
- Might be relevant: my neovim config can be found [here](https://github.com/pelegs/neovim_config)

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue!

I'm not able to reproduce the issue, could you let me know:
- How do you quit Neovim, and do you have some other buffers open?
- Do you have any plugin that do something when quiting Vim? e.g. a session manager, things that write files somewhere

**Comment by shortcuts** [comment]
Looking at the error it might have something to do with https://vim.fandom.com/wiki/Make_views_automatic and https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/util/win.lua#L122
