### ISSUE TITLE
Documentation of vim-plug install

### ISSUE THREAD

**Issue by TomDeneire** [shortcuts/no-neck-pain.nvim#116]
## Description

No double quotes allowed in vim-plug install commands

## Steps to reproduce

1. https://github.com/shortcuts/no-neck-pain.nvim/blob/main/README.md contains double quotes instead of single ones

## Correction

correct version = 

```
-- stable version
Plug 'shortcuts/no-neck-pain.nvim', { 'tag': '*' }
-- dev version
Plug 'shortcuts/no-neck-pain.nvim'
```

**Comment by shortcuts** [comment]
Hey, thanks for the issue :D 

Good catch, would you mind opening a PR with the changes?
