### ISSUE TITLE
Too long returning to NNP mode

### ISSUE THREAD

**Issue by kaiphat** [shortcuts/no-neck-pain.nvim#119]
## Description

I had shortcut for buffer closing `map('n', ',x', ':wq<cr>')`. When i open two buffers with vertical split NNP mode is disabled. Then two ways:
1 - i close buffer with `:q` or `:wq` and return to NNP mode. It's normal.
2 - i close buffer using shortcut, then nvim returns to NNP mode only after ~5s.

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue!

I'll try to reproduce, but I don't see how it would impact the plugin if it does the same thing under the hood.

Could you please let me know which versions you are using?
- Neovim version: [e.g. 0.5.x / 0.6.x / 0.7.x / 0.8.x / Nightly]
- no-neck-pain.nvim version: [e.g. latest / 0.1.2 / dev]

**Comment by kaiphat** [comment]
```
- NVIM v0.9.0-dev-155+g771824128
- dev version
```

**Comment by shortcuts** [comment]
Just tried on `v0.8.2` and can confirm it's exactly the same behavior with `:wq` and `,x`, I wonder if it's an upstream issue on 0.9, will try it further ASAP!

**Comment by kaiphat** [comment]
Actually i don't know why, but now it's working correctly, thank you!

**Comment by shortcuts** [comment]
> Actually i don't know why, but now it's working correctly, thank you!

Enjoy :D
