### ISSUE TITLE
White line if backgroundColor = nil

### ISSUE THREAD

**Issue by kaiphat** [shortcuts/no-neck-pain.nvim#120]
## Description

White line if `backgroundColor = nil`.
![image](https://user-images.githubusercontent.com/53742299/210521378-4405e98e-5d03-4b6b-80fa-241ca22db10c.png)

How can i change it, but save transparent?

**Comment by shortcuts** [comment]
Hey, could you check if https://github.com/shortcuts/no-neck-pain.nvim/issues/104 is related?

**Comment by kaiphat** [comment]
I saw this issue, and it's about my problem:) In this issue man just disabled transparent background, but i want to use transparent and set `Normal = { bg = 'none' }`.

**Comment by shortcuts** [comment]
> I saw this issue, and it's about my problem, but...:) In this issue man just disabled transparent background, but i want to use transparent and set `Normal = { bg = 'none' }`.

yep make sense! I think we should just do nothing to the background if `nil` is provided

**Comment by shortcuts** [comment]
sorry the issue took long to resolve, I had some stuff to do!

this should be properly fixed in https://github.com/shortcuts/no-neck-pain.nvim/releases/tag/v0.7.0
