### ISSUE TITLE
[feat] Open scratch pad buffer like norg file

### ISSUE THREAD

**Issue by kaiphat** [shortcuts/no-neck-pain.nvim#121]
Open scratch pad buffer like norg file

**Comment by shortcuts** [comment]
Could you provide more explanation of what you expect? The file type? A whole template file?

**Comment by kaiphat** [comment]
It can be always the same file with norg type. For example scratch.norg.
Norg file is very comfortable for notes creating.
You can see it here: https://github.com/nvim-neorg/neorg

**Comment by kaiphat** [comment]
Of course it should be optional feature.

**Comment by shortcuts** [comment]
If it only requires having neorg installed and a norg filetype, you could define it like this and the side buffer should be valid

```lua
require("no-neck-pain").setup({
        bo = {
            filetype = "norg",
        },
})
```

Let me know if this works :D

**Comment by kaiphat** [comment]
There are correct highlights but symbols wasn't changed.

**Comment by kaiphat** [comment]
![Uploading image.png…]()

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/210754693-738e7eac-f8ac-4296-9d2e-425d6d64f15b.png)

**Comment by shortcuts** [comment]
Ok make sense, I believe there's other options that should be added to make it work properly.
