### ISSUE TITLE
[BUG] Cannot use :NoNeckPain command because it does not exist.

### ISSUE THREAD

**Issue by SandNoodle** [shortcuts/no-neck-pain.nvim#137]
## Description

There is no NoNeckPain command, which makes it impossible to use the plugin.

## Steps to reproduce

1. Install plugin via Plug
1. Reload config (ex. source $MYVIMRC) or restart Neovim
3. Type :NoNeckPain
4. Neovim displays "E492: Not an editor command: NoNeckPain"

## Expected behavior

I've expected the plugin to work - buffer to become centred.

## Environment

- Neovim version: 0.5.1
- no-neck-pain.nvim version: latest
- Plugin clash: n/a

**Comment by shortcuts** [comment]
Hey! Thanks for opening the issue :D 

Indeed the command I use is only available in 0.7 and above, I've opened a PR to fix it

**Comment by shortcuts** [comment]
please let me know if it correctly fixes your issue!

**Comment by SandNoodle** [comment]
Hi, this does indeed register NoNeckPain command, but instead there's an error (nil value) in main.lua:66 for field nvim_create_augroup

![image](https://user-images.githubusercontent.com/34868657/212204966-5135fd16-9737-4115-bf1a-bc1a89d653c2.png)
