### ISSUE TITLE
Follow textwidth (tw)

### ISSUE THREAD

**Issue by 4e554c4c** [shortcuts/no-neck-pain.nvim#155]
## Describe the problem

Currently the `width` of no-neck-pain has to be specified globally. However, I use several different languages and projects, each with different width standards. For example, Lean projects usually like to have a maximum text width of 100 characters. C projects usually stick to 80 characters, and so does my personal writing.
I keep track of all of these with the `'texwidth'` variable.

## Describe the solution

There should be an option for `no-neck-pain.nvim` to follow the texwidth variable instead of simply following a global width.

**Comment by shortcuts** [comment]
Hey! Thanks for opening the issue :D 

This seems pretty feasible, I just need to find a correct API to expose. Would you mind explaining how you use this option?
- Do you define it every time you open Nvim, or is it defined at your config level?
- Would you expect the `width` to exactl match the `textwidth`?

**Comment by shortcuts** [comment]
https://github.com/shortcuts/no-neck-pain.nvim/pull/156 should cover this issue, waiting for some more insights from you on the two questions above before merging

**Comment by 4e554c4c** [comment]
Hi! thanks for working on this.

Usually I have textwidth defined in `ftplugin`s, so it isn't always defined on nvim startup. For example consider
1.  you open `nvim src/file.c`, so `tw=80`.
2. you decide some documentation fixes are necessary, so you `:e README.md` with a modeline of `vim: tw=90`.

Because it needs to be different for different kinds of buffers, I'm not sure if this option can be set in the `setup` function (like in #156).


Regarding whether `tw=width` exactly.... that's a good question. I think it depends on filetype. e.g. for programming languages I would probably want the width to be 10 chars or so more than `tw` (so you can see the beginning of non-wrapped text). But this is not a requirement for this issue.

**Comment by shortcuts** [comment]
Thanks for giving more details! I guess this will need a bit of investigation of what to do for a full support.

I've exposed a resize command that should suit your need for the short term, however there should be a better solution!

**Comment by shortcuts** [comment]
I still added support for `textwidth` and `colorcolumn` as it provides some great benefits to make usage more consistent across different file types, along with the resize command it should cover a lot of use cases.

I'll now work on providing an option the user can enable to resize when the filetype changes, so the plugin would adapt to the two options

**Comment by Shooooooooo** [comment]
When I do
`require("no-neck-pain").setup {
  width = "textwidth",
}`
I am getting the following error
`E5113: Error while calling lua chunk: .../nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/config.lua:392: `width` must be greater than 0.`
Am I setting it up wrong?
