### ISSUE TITLE
Allow setting reserved padding width

### ISSUE THREAD

**Issue by goingtosleep** [shortcuts/no-neck-pain.nvim#161]
## Describe the problem

I have a workflow like this:
(1) When I open nvim in full-screen (ui_width=255), I'd like `no-neck-pain` to open a left padding of width=84 (about 33%).
(2) When I open a single file, I snap it to the right/left half of the screen, then the terminal's width is 127. In this case, I don't want `no-neck-pain` to open any padding.

I tried setting option `NoNeckPain.config.width = 128` and (2) works, no padding when the terminal is snapped to half screen. However, when I resize the terminal to full-screen, the left padding only has width=63, not 84. Therefore, the text is shifted a bit to the left, harder to read.

The interesting thing is, when I don't set `NoNeckPain.config.width`, the left padding is 84, but the snapped terminal has left padding in this case.

## Describe the solution

I read the code a bit and see [this line](https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/wins.lua#L249). The padding is calculated from the `NoNeckPain.config.width`, so the larger the width, the smaller the padding. I'm not sure if I got the intention, but isn't it better if we do something like `math.floor(width * NoNeckPain.config.reserved_padding_percentage - paddingToSubstract)`? Then one can set `reserved_padding_percentage = 0.33` in the config. What do you think?

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue!

> However, when I resize the terminal to full-screen, the left padding only has width=63, not 84. Therefore, the text is shifted a bit to the left, harder to read.

This seems expected if you have enabled each side buffers, as it would mean there's `127` width left, `63` on each side.

> I'm not sure if I got the intention, but isn't it better if we do something like math.floor(width * NoNeckPain.config.reserved_padding_percentage - paddingToSubstract)? Then one can set reserved_padding_percentage = 0.33 in the config. What do you think?

To me it's a different approach. In this plugin, `width` defines "the width of the main focused window", I thought it would be easier for users to define it, as it could match to the maximum length of a line or things like this.

Your solution could work, but it seems a bit harder to use for a user, or maybe I did not get the usage?

**Comment by goingtosleep** [comment]
Oh ok I see. It makes more sense when I enable both sides. But seems like there is some confusion in the definition of `width`:
- the width of the main focused window (you wrote above).
- the width that when the terminal size is smaller than it, we don't create side buffers.

I only use left buffer, and now I'm setting `width` as the latter definition to prevent creating side buffer when terminal size is `127` (half screen). The goal I want is to remove the padding in the picture below, without making the padding smaller in full-screen mode.

![image](https://user-images.githubusercontent.com/47395035/215927622-a0dfd42d-78a8-4328-9022-72506173503e.png)

What do you think 😊?

**Comment by shortcuts** [comment]
> I only use left buffer, and now I'm setting width as the latter definition to prevent creating side buffer when terminal size is 127 (half screen). The goal I want is to remove the padding in the picture below, without making the padding smaller in full-screen mode.

Indeed it's weird, if the screen is 255 and you've set 127 or 128 there shouldn't be padding, I'll try to reproduce locally and see if it's a confirmed bug!

**Comment by shortcuts** [comment]
note: maybe instead of checking if the terminal width can host `width` + side buffer, it should add a small arbitrary value like `10` since a padding of 10 wouldn't bring much to the user.

**Comment by shortcuts** [comment]
ok so indeed things that might make sense on smaller screens (picture 1), might not make sense on larger ones (picture 2), which are both snapped to the side of the screen, taking ~50% of the width.

As Vim is not aware of the screen size, it makes sense not to be able to support those behaviors, but we could introduce a "minimal acceptable padding" value to decide displaying them or not (picture 2 has a padding of 5 for example, which is pretty much irrelevant)

<img width="1280" alt="Screenshot 2023-02-01 at 22 56 06" src="https://user-images.githubusercontent.com/20689156/216172391-2b4a764b-46c1-4ebc-ba90-735ae7e09f77.png">

<img width="1280" alt="Screenshot 2023-02-01 at 22 56 32" src="https://user-images.githubusercontent.com/20689156/216172482-5b0d07ee-cf02-41b6-879f-5913f8977124.png">
