### ISSUE TITLE
Doesn't play well with dashboard-nvim

### ISSUE THREAD

**Issue by BerkeleyTrue** [shortcuts/no-neck-pain.nvim#17]
If I open vim without a buffer selected, I should see my dashboard.

Instead I see my dashboard quickly pushed to the right and I'm left with an empty buffer. Further file openings show no NNP.

If I open vim with a file selected, it works fine.

**Comment by shortcuts** [comment]
Thanks for testing the plugin!

> Instead I see my dashboard quickly pushed to the right and I'm left with an empty buffer. Further file openings show no NNP.

I'll try to reproduce, was it by manually toggling NNP or with the VimEnter hook?

**Comment by BerkeleyTrue** [comment]
It was the VimEnter hook. 

Maybe I can exclude no name buffers from augroup pattern?

**Comment by shortcuts** [comment]
Did some investigation and realized `dashboard-nvim` does not support split/vsplit on the dashboard buffer, so indeed we can't trigger NNP from there.

I'll try to find a hook that can trigger on BufWinEnter without causing infinite calls, thanks for the information!

> Maybe adding a check in the "BufWinEnter" autocmd for "buf_get_name() == ''" would prevent the issue with Dashboard.

I'm afraid it would impact all no-named buffers, I see this check on their side that would maybe be reusable:

https://github.com/glepnir/dashboard-nvim/blob/master/lua/dashboard/events.lua#L67-L69

**Comment by shortcuts** [comment]
@BerkeleyTrue feel free to give a try at the new snippet, it should cover the dashboard case!
