### ISSUE TITLE
Trigger plugin to toggle on / off when window size changes

### ISSUE THREAD

**Issue by DGmip** [shortcuts/no-neck-pain.nvim#172]
## Describe the problem

I use a tiling window manager so i'm constantly switching between a small window and full screening windows to work on them, i have to toggle nnp every time i switch between the window sizes

## Describe the solution

set a resolution value to auto/force toggle nnp on, and anything other than that it resolves back to whatever state it was in before the resolution change

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue!

I'm not sure I get the full picture here. You shouldn't have to disable the plugin, as it automatically hides side buffers if there's not enough space remaining.

Would you mind providing a bit more context on the expectations?

**Comment by shortcuts** [comment]
actually reading the issue again, maybe https://github.com/shortcuts/no-neck-pain.nvim/pull/173 also solves your issue?

**Comment by shortcuts** [comment]
closing the issue as it have been stalled for some time, feel free to re-open if necessary!
