### ISSUE TITLE
Width shrink after toggle nvim-tree

### ISSUE THREAD

**Issue by LintaoAmons** [shortcuts/no-neck-pain.nvim#174]
## Description

Width shrink after toggle nvim-tree, as shown in the gif. I expect the width is always same with my config

![no-neck-pain](https://user-images.githubusercontent.com/95092244/218237516-67ac5961-89e1-46ea-893f-6920a82e70d9.gif)

## Environment

- Neovim version: 0.8.x
- no-neck-pain.nvim version: latest

**Comment by shortcuts** [comment]
Hey there, thanks for reporting the issue! I can definitely reproduce and working on a fix :D
