### ISSUE TITLE
Clean up the side buffer 

### ISSUE THREAD

**Issue by LintaoAmons** [shortcuts/no-neck-pain.nvim#179]
## Describe the problem

The `~` at the side buffer is kind of ugly, maybe remove this to make it more clean?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/95092244/218286723-23d2a2d9-6997-48a4-9c78-739b4c7de56c.png">

**Comment by shortcuts** [comment]
Hey, this should be the case already, do you load NNP before loading your theme? If so, it might override the highlight groups we set.

**Comment by shortcuts** [comment]
closing the issue as it have been stalled for some time, feel free to re-open if necessary!
