### ISSUE TITLE
Suggestion: Add names to buffers

### ISSUE THREAD

**Issue by BerkeleyTrue** [shortcuts/no-neck-pain.nvim#18]
Currently Buffers show up with no name. It would be real cool if they said "no-neck-pain"

![image](https://user-images.githubusercontent.com/6775919/206813327-04038cdf-782e-461f-bd5d-502507ac3a98.png)

**Comment by shortcuts** [comment]
Thanks for testing the plugin!

> It would be real cool if they said "no-neck-pain"
Make sense! Sadly we can't have multiple buffers with the same name but I could append `-left` and `-right`

Linking https://github.com/shortcuts/no-neck-pain.nvim/issues/15 for visibility, which aims at make side buffers configurable

**Comment by shortcuts** [comment]
Side note: side buffers are not even on your screenshot, is it because it's cropped or they were not the same size?

**Comment by BerkeleyTrue** [comment]
Oh, my screen is super wide so I just cropped the relevant stuff. Yes, they are even.

**Comment by BerkeleyTrue** [comment]
Works great!
