### ISSUE TITLE
Invalid ColorCode

### ISSUE THREAD

**Issue by Freyskeyd** [shortcuts/no-neck-pain.nvim#184]
## Description

Hello, I encounter an issue regarding the start of the plugin. I updated my onenord them using packer and now I have an error for a missing value:

```
packer.nvim: Error running config for no-neck-pain.nvim: ...acker/start/no-neck-pain.nvim/lua/no-neck-pain/color.lua:57: `colorCode` none  does not match the regex ^#[abcdef0-9][abcdef0-9][abcdef0-9][abcdef0-9][abcdef0-9][abcdef0-9]$

```

I tried to find how to fix it but without success, does it ring a bell to someone?

**Comment by shortcuts** [comment]
Hey there, thanks for opening the issue!

What does your `setup` call look like? Did you provided a custom `backgroundColor` value?

**Comment by Freyskeyd** [comment]
Hello, 

Sorry I should have put the config, here it is:

```lua
use {"shortcuts/no-neck-pain.nvim", tag = "*", config = function()
    require("no-neck-pain").setup({
      width = 250,
    })
  end}
```

I didn't update much and I'm using `onenord` without any modifications

**Comment by shortcuts** [comment]
guess for anyone that wants to work on a fix, or me this evening:


- we might get `NONE` returned here: https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/color.lua#L70 
  - if so, this should check it https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/color.lua#L73
  - if not, this condition might be wrong


if none of the above apply, either:
- we are not correctly getting the current background color
- onenord doesn't set their background to this highlight group?

**Comment by shortcuts** [comment]
can confirm I'm not able to reproduce without the `onenord` theme, will try with it

**Comment by shortcuts** [comment]
neither with it, is your config open-source? I'll however still work on making it non-blocking

**Comment by thenbe** [comment]
I encounter the same issue while using `nvchad` config so perhaps that can help with issue repro.

> https://github.com/NvChad/NvChad
> docker quick-start: https://nvchad.com/quickstart/install#try-in-docker-container

**Comment by shortcuts** [comment]
thanks for reporting! is the config similar to the one of the issue?

**Comment by shortcuts** [comment]
found the issue! the fix is available in 0.9.2 :)

**Comment by Freyskeyd** [comment]
Thanks a lot @shortcuts !

**Comment by shortcuts** [comment]
Thanks both of you for using the plugin :D
