### ISSUE TITLE
Buffers remain open when work buffer is closed

### ISSUE THREAD

**Issue by BerkeleyTrue** [shortcuts/no-neck-pain.nvim#20]
If I open a file to edit, NNP is activated.

If I then close this file, I'm left with the empty side buffers created by NNP. 

I'm not sure how hard this is, but it be great if these where the last buffers open, that they'd close themselves.

**Comment by shortcuts** [comment]
oh this is weird, normally NNP should trigger a disable if you close of the main buffer (left, curr or right)

I'm not able to reproduce locally, could you provide some steps?

**Comment by shortcuts** [comment]
Ah indeed it stays open when using `BufferClose`, should work well with `:q`

**Comment by shortcuts** [comment]
Hey @BerkeleyTrue, which command/key do you use to kill the buffer? It would be great for me to properly reproduce

**Comment by BerkeleyTrue** [comment]
Apologies, I'm just using `:q`

**Comment by shortcuts** [comment]
> Apologies, I'm just using `:q`
> 
> 

Made a lot of tests and with the above option it should disable it (hopefully!)
