### ISSUE TITLE
Neo-tree show/close commands outdated

### ISSUE THREAD

**Issue by RANKSHANK** [shortcuts/no-neck-pain.nvim#212]
`   Error  09:28:38 msg_show.lua_error Error executing Lua callback: ...e/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/trees.lua:74: Vim:E492: Not an editor command: NeoTreeClose`
I'm getting a non existent command error attempting to toggle this while neotree is open

https://github.com/shortcuts/no-neck-pain.nvim/blob/2a2b69edd4b64facb25535f6f2d9af0155b515a8/lua/no-neck-pain/trees.lua#L11-L12
It looks like here is where the culprits are, these were [deprecated in neo-tree 2.0](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Changelog#20), not sure if there was a recent neo-tree commit removing the vim commands or if it was the fixes in #191 bringing the issue to light, but following the new [neo-tree arg spec](https://github.com/nvim-neo-tree/neo-tree.nvim#arguments) it should be:
`Neotree close` instead of `NeoTreeClose`
`Neotree show` instead of `NeoTreeReveal`

**Comment by shortcuts** [comment]
Hey, thanks for opening this issue!

This is weird that you have this issue, the `NeoTreeClose` and `NeoTreeReveal` commands are still available 🤔 

I'll however still switch to the new format, so thanks for pointing this out!

**Comment by shortcuts** [comment]
released in [1.2.0](https://github.com/shortcuts/no-neck-pain.nvim/releases/tag/v1.2.0), sorry for the inconvenience!

**Comment by RANKSHANK** [comment]
Thanks for the quick fix and the great addon
