### ISSUE TITLE
Feature request: set winhighlight in config.buffers.colors

### ISSUE THREAD

**Issue by catgoose** [shortcuts/no-neck-pain.nvim#214]
Allow setting a string for winhighlight for the side buffers, such as:

```lua
winhiglight = "Normal:NormalNC,WinBar:NormalNC"

```

This would allow a user to easily set colors for the buffer according to their colorscheme without specifying the colors manually.

**Comment by shortcuts** [comment]
This should be addressed by the proposed solution above
