### ISSUE TITLE
Side buffers preserve previous theme colors after changing theme

### ISSUE THREAD

**Issue by Strus** [shortcuts/no-neck-pain.nvim#222]
## Description

It seems that no-neck-pain saves the colors of the original color scheme after calling `setup()`, and there is no way to change them automatically after changing the color scheme. Calling `setup()` again has no effect.

## Steps to reproduce

1. Enable no-neck-pain
2. Change colorscheme using `:colorscheme <theme>` command
3. Observe that all buffers changed colors
4. Disable and enable no-neck-pain
5. Observe that no-neck-pain buffers now have colors from the previous colorscheme, not the current one

## Expected behavior

No-neck-pain buffers colors are always synced with active colorscheme
OR
There is a way to tell no-neck-pain to "reinit" after changing the colorscheme.

## Environment

- Neovim version: 0.9
- no-neck-pain.nvim version: latest

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue! I'll investigate if it's possible to trigger a refresh when the colorscheme changes, otherwise I can indeed provide a small method. 

Could you share your setup config please so I can properly reproduce?

**Comment by shortcuts** [comment]
released in 1.2.2! you can now enable an autocmd to refresh the state when a colorscheme changes

**Comment by Strus** [comment]
Nice! Thank you.
