### ISSUE TITLE
Invalid Tab Page ID State and Unexpected Events with "enableOnTabEnter" autocmd

### ISSUE THREAD

**Issue by wroyca** [shortcuts/no-neck-pain.nvim#229]
## Description

NoNeckPain's enableOnTabEnter autocmd fails to activate properly on subsequent tabs and occasionally generates an Invalid Tab Page ID State error.

## Steps to reproduce

1. Spam tabnew and tabclose
2. Notice that NoNeckPain is not activated for all tabs.
3. Notice that we occasionally trigger persistent Invalid Tab Page ID State.
4. ... 

Upon conducting some debugging, it became apparent that we are encountering an invalid tab page ID state, specifically with regards to stateWinsActive. It is probable that there are race conditions resulting from vim.schedule(function() end). However, what is unusual is the occurrence of "QuitPre" and "BufDelete" events being triggered with the "tabnew" command:

```bash
Error executing vim.schedule lua callback: ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: Invalid tab ID '5'. Available tab IDs: 1, 4, 7, 8, 9                                             
stack traceback:
        [C]: in function 'error'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: in function 'stateWinsActive'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:185: in function <...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:179>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: Invalid tab ID '6'. Available tab IDs: 1, 4, 7, 8, 9
stack traceback:
        [C]: in function 'error'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: in function 'stateWinsActive'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:185: in function <...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:179>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: Invalid tab ID '5'. Available tab IDs: 1, 4, 7, 8, 9
stack traceback:
        [C]: in function 'error'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: in function 'stateWinsActive'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:185: in function <...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:179>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: Invalid tab ID '6'. Available tab IDs: 1, 4, 7, 8, 9
stack traceback:
        [C]: in function 'error'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:389: in function 'stateWinsActive'
        ...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:185: in function <...re/nvim/lazy/no-neck-pain.nvim/lua/no-neck-pain/main.lua:179>
```

[Screencast from 2023-06-23 16-53-55.webm](https://github.com/shortcuts/no-neck-pain.nvim/assets/91024200/e751e43c-3d96-4c8f-942e-97901e0a95d9)

[Screencast from 2023-06-23 16-56-17.webm](https://github.com/shortcuts/no-neck-pain.nvim/assets/91024200/7ab2287a-a6eb-4c8d-82df-c14c05cdc5a9)

## Expected behavior

Treat new tabs as isolated instance - that is, if a new tab is created, NoNeckPain enabled, and then subsequently closed, returning to the previous buffer should not result in it being centered.

## Environment

- Neovim version: NVIM v0.9.1
- no-neck-pain.nvim version: 1.2.2
- Plugin clash: Anything with tabs, e.g. neogit.

![image](https://github.com/shortcuts/no-neck-pain.nvim/assets/91024200/83a59abe-064d-4085-b0ec-fc6f1b812cc0)

**Comment by shortcuts** [comment]
Hey, thanks a lot for the issue, love the description and reproduction, it helped me finding the solution pretty quickly!

https://github.com/shortcuts/no-neck-pain.nvim/pull/231 seems to fix it, but it would be great if you could try the latest version on your side just to confirm

**Comment by shortcuts** [comment]
love to hear it! made some more improvements which will be released in the next version https://github.com/shortcuts/no-neck-pain.nvim/pull/232
