### ISSUE TITLE
Cursor placed inside buffer instead of file

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [shortcuts/no-neck-pain.nvim#237]
## Description
When I open a file two buffers open on the side to center the screens. But my cursor is placed on the left buffer instead.

## Steps to reproduce

1. Install this plugin with lazy.
2. Install [daylight.nvim ](https://github.com/NTBBloodbath/daylight.nvim) and have these settings for its config

```lua
      require("daylight").setup({
        day = {
          name = "sweetie",
          time = 8, -- 8 am ---- <---- CHANGE THIS TO 12 AM YOUR TIME
        },
        night = {
          name = "gruvbox",
          time = 19,    --- <--- CHANGE THIS TO YOUR CURRENT TIME
        },
        interval = 60000, -- Time in milliseconds, 1 minute
      })
```

 but change the colorschemes to the ones you actually have installed on your system. Follow the arrows and comments. The purpose is to get daylight to change your colorscheme.

3. Have these configuration options.

```lua
  {
    "shortcuts/no-neck-pain.nvim",
    version = "*",
    event = "ColorScheme",
    opts = {
      width = 80,
      background = bg,
      autocmds = {
        enableOnVimEnter = false,
      }
    },
    config = function()
      vim.cmd("NoNeckPain")
    end
  }
```

## Expected behavior

When I open a buffer, the cursor is at the center buffer.

## Environment

- Neovim version: NVIM v0.9.1
- no-neck-pain.nvim version: latest stable.
- Plugin clash: Unsure but it may be daylight.nvim

**Comment by shortcuts** [comment]
Hey @AlphabetsAlphabets thanks for opening the issue!

Looking at your NNP configuration, it seems like it refreshes the plugin on `event = "ColorScheme"`, _I guess_ this is where the issue is, you could leverage `autocmds.reloadOnColorSchemeChange` which will automatically refreshes NNP if the scheme changes

let me know if that helps!

**Comment by AlphabetsAlphabets** [comment]
@shortcuts thanks for the quick reply. I tried a few different configuration options
1. Removing `event = "ColorScheme"` and setting `reloadOnColorSchemeChange = true`.
2. Adding `event = "ColorScheme"` and setting `reloadOnColorSchemeChange = false`. Which is what you suggested.

However, my cursor stills shows up on the left buffer. Also from what I understand, setting `event = ColorScheme` and `reloadOnColorSchemeChange = true` is the same thing, yeah?

**Comment by shortcuts** [comment]
> Which is what you suggested.

Actually what I suggested was `1.`

> setting event = ColorScheme and reloadOnColorSchemeChange = true is the same thing, yeah?

exactly, you don't need the `Event` trigger for NNP and just leverage `reloadOnColorSchemeChange`

---

I was not able to reproduce the issue of the wrong position, here's my config just in case

```lua
return {
    {
        "shortcuts/no-neck-pain.nvim",
        lazy = false,
        dev = true,
        opts = {
            autocmds = {
                enableOnVimEnter = true,
                enableOnTabEnter = true,
                reloadOnColorSchemeChange = true,
            },
            mappings = {
                enabled = true,
                toggle = "<Leader>kz",
            },
            buffers = {
                left = {
                    bo = {
                        filetype = "md",
                    },
                    scratchPad = {
                        enabled = false,
                        fileName = "notes",
                        location = "~/",
                    },
                },
            },
        },
    },
}
```

```lua
return {
    {
        "NTBBloodbath/daylight.nvim",
        lazy = false,
        opts = {
            day = {
                name = "carbonfox",
                time = 8, -- 8 am ---- <---- CHANGE THIS TO 12 AM YOUR TIME
            },
            night = {
                name = "nightfox",
                time = 21,    --- <--- CHANGE THIS TO YOUR CURRENT TIME
            },
            interval = 10000, -- Time in milliseconds, 1 minute
        }
    }
}
```

**Comment by AlphabetsAlphabets** [comment]
I see... How do you start NNP? Because I have it start automatically at the very end of my `init.lua` with `vim.cmd("NoNeckPain")`.

**Comment by AlphabetsAlphabets** [comment]
Hi @shortcuts do you have the time to deal with this? Sorry, I don't mean to sound rude or anything. I'd just like this fixed, I get that you may have other things to deal with.

**Comment by shortcuts** [comment]
Hey! 

> How do you start NNP?

I have the [autocmds option](https://github.com/shortcuts/no-neck-pain.nvim#-configuration) enabled, `autocmds.enableOnVimEnter = true`

> do you have the time to deal with this?

Sure, but if you wish to contribute don't hesitate to, during weekdays I'm at my job so I don't always have time in the evening, but will definitely look at it!

**Comment by AlphabetsAlphabets** [comment]
> Sure, but if you wish to contribute don't hesitate to, during weekdays I'm at my job so I don't always have time in the evening, but will definitely look at it!

Sure no problem at all. Now I have this new config and the issue is still the same. What's more is that despite setting `enableOnVimEnter = true` I have to use the `<leader>z` keybinding manually.

```lua
  {
    "shortcuts/no-neck-pain.nvim",
    lazy = false,
    version = "*",
    opts = {
      width = 80,
      background = vim.g.colors_name,

      autocmds = {
        enableOnVimEnter = true,
        enableOnTabEnter = true,
        reloadOnColorSchemeChange = true,
      }
    },
    config = function()
      vim.keymap.set("n", "<leader>z", function() vim.cmd("NoNeckPain") end)
    end
  },
```

**Comment by shortcuts** [comment]
> What's more is that despite setting `enableOnVimEnter = true` I have to use the `<leader>z` keybinding manually.

Wow this is super weird, I run almost the same exact config and can't reproduce, here's mine

```lua
return {
    {
        "shortcuts/no-neck-pain.nvim",
        lazy = false,
        opts = {
            width = 70,
            autocmds = {
                enableOnVimEnter = true,
                enableOnTabEnter = true,
                reloadOnColorSchemeChange = true,
            },
            mappings = {
                enabled = true,
                toggle = "<Leader>kz",
            },
            buffers = {
                left = {
                    bo = {
                        filetype = "md",
                    },
                    scratchPad = {
                        enabled = false,
                        fileName = "notes",
                        location = "~/",
                    },
                },
                right = {
                    enabled = false,
                },
            },
        },
    },
}
```

btw I see you use `config` from lazy, you can also set `mappings.enabled = true` and `mappings.toggle = "<leader>z" if you wish

----

could you send me your dotfile repository if you have one? i'll try to reproduce with your setup

**Comment by AlphabetsAlphabets** [comment]
> could you send me your dotfile repository if you have one? i'll try to reproduce with your setup

Sure no problem. https://github.com/AlphabetsAlphabets/nvim

**Comment by shortcuts** [comment]
> > could you send me your dotfile repository if you have one? i'll try to reproduce with your setup
> 
> Sure no problem. https://github.com/AlphabetsAlphabets/nvim

OK so I've did some other tries and it looks like it's because of the `config` method call. TBC on the Lazy.nvim configuration side, but one shouldn't use both `config` and `opts`. Basically `opts` is forwarded to the `setup` func, while `config` requires you to call the `setup` func.

Here's what your config should look like for NNP:

```lua
  {
    "shortcuts/no-neck-pain.nvim",
    lazy = false,
    version = "*",
    opts = {
      width = 80,
      autocmds = {
        enableOnVimEnter = true,
        enableOnTabEnter = true,
        reloadOnColorSchemeChange = true,
      },
      mappings = {
          enabled = true,
          toggle = "<leader>z",
      },
    },
  },
```

let me know how that goes :)
