### ISSUE TITLE
Change width of active window when there are multiple splits

### ISSUE THREAD

**Issue by alex35mil** [shortcuts/no-neck-pain.nvim#239]
First of all, brilliant plugin. Thanks for creating it!

## Describe the problem
`NoNeckPainWidthUp/Down` work great with a single window, but it does't do anything when there are multiple splits.

## Describe the solution
When there are multiple splits, it changes width of the active one.

**Comment by shortcuts** [comment]
> First of all, brilliant plugin. Thanks for creating it!

thanks, glad you like it 💓 

> `NoNeckPainWidthUp/Down` work great with a single window, but it does't do anything when there are multiple splits.

is there the empty side buffers at this point still? it seems to behave correctly on my side, here's how I tried to reproduce the issue:
1. open nvim
2. toggle NNP
3. call either `:split` or `:vsplit`
     - side buffers are still open
5. call either `:NoNeckPainWidthUp`, `NoNeckPainWidthDown` or `NoNeckPainResize INT`
6. see side buffers growing/reducing

> 
> ## Describe the solution
> When there are multiple splits, it changes width of the active one.

**Comment by alex35mil** [comment]
Ah, the issue is that the side buffers are gone and that's how plugin changes width.

I workarounded it [this way](https://github.com/alex35mil/dotfiles/blob/a0c9d3092eda3281cf12a97a9f37b72a89834ce6/user/cfg/nvim/lua/actions/editor.lua#L3-L22) but it's incorrect as I need to check if side buffers are visible and pick correct command accordingly. Gonna fix it in a sec.

**Comment by alex35mil** [comment]
Alright, this seems to be working: https://github.com/alex35mil/dotfiles/commit/61f2a440aac01535aca9f751a067655dc3ee9cdb

**Comment by shortcuts** [comment]
> Ah, the issue is that the side buffers are gone and that's how plugin changes width.
> I workarounded it [this way](https://github.com/alex35mil/dotfiles/blob/a0c9d3092eda3281cf12a97a9f37b72a89834ce6/user/cfg/nvim/lua/actions/editor.lua#L3-L22)

That make sense, the NNP resize is only to adjust the side buffers width, so if they are absent you need to default to the neovim builtin way.

FYI I expose the NNP state in the `_G` global variable so your "are_sidenotes_visible` could check for something like `_G.NoNeckPain.state.tabs[1].wins.main.right || _G.NoNeckPain.state.tabs[1].wins.main.left`, where `1` is the tabID, `1` being the default tab, but you can call `vim.api.nvim_get_current_tabpage()` to retrieve the ID too

**Comment by alex35mil** [comment]
Gotcha, thanks!
