### ISSUE TITLE
[feat] Support rcarriga/nvim-dap-ui

### ISSUE THREAD

**Issue by fnune** [shortcuts/no-neck-pain.nvim#241]
## Describe the problem

When I open `nvim-dap-ui` and then call `:NoNeckPain`, all `nvim-dap-ui` windows are squished together. Additionally, when running `:NoNeckPain` again, the `nvim-dap-ui` windows are overly expanded and the main window remains the width of a no-neck-pain-enabled window:

https://github.com/shortcuts/no-neck-pain.nvim/assets/16181067/8f65dfa6-4e1b-4178-9f30-1b364d2f37ec

## Describe the solution

Support `nvim-dap-ui` so that enabling and disabling `:NoNeckPain` respects the layout of the existing `nvim-dap-ui` windows.

**Comment by shortcuts** [comment]
Hey, thanks for reporting! I can confirm this doesn't behave correctly, I'm working on it :D
