### ISSUE TITLE
Buffer delete command does not work

### ISSUE THREAD

**Issue by jfab20** [shortcuts/no-neck-pain.nvim#243]
## Description

If I open two or more buffers, say ``file1.md``
and  ``file2.md``, and I run NNP, then when I do ``:bd`` on
one of them, say on ``file1.md``, then NNP closes and the
buffer gets replaced by a new buffer "[No Name]".

## Steps to reproduce

1. Open two files 
2. Do ``:bd``
3. NNP gets closed and a new buffer gets created

## Expected behavior

I want the behaviour just as if NNP wasn't running, meaning
``:bd`` just closes the buffer and I get sent to my other
opened buffer, with NNP *still* running.

## Environment

- Neovim version: 0.9.2
- no-neck-pain.nvim version: 1.2.3

**Comment by shortcuts** [comment]
Hey, so far it seems not possible to fix it, [as per Neovim doc `Any windows for this buffer are closed.`](https://neovim.io/doc/user/windows.html#:~:text=Any%20windows%20for%20this%20buffer%20are%0A%09%09closed.), I'll try to see if a workaround is possible but can't confirm I'll make it work!

**Comment by hqkhan** [comment]
I'm running into this issue as well. Why does `:bd` without NNP work fine but with NNP is different? 

Maybe some hack with auto command would work on a buffer delete where it scans the rest of buffers to go to?

**Comment by shortcuts** [comment]
I've started iterating on `bd` support in https://github.com/shortcuts/no-neck-pain.nvim/pull/281, but as I'm not 100% confident that all use cases has been covered, i've made it available under an option named `fallbackOnBufferDelete`, set it to `true` to try it!

Thanks for reporting and using the plugin :D

**Comment by hqkhan** [comment]
Thank you for working on this! I tried it and I still have the same experience as before. 

Here's my config:

```
local M = {
  "shortcuts/no-neck-pain.nvim",
  version = "*",
  -- "VeryLazy" hides splash screen
  event = "BufReadPre",
}

M.config = function()
  require("no-neck-pain").setup({
    options = {
        fallbackOnBufferDelete = true,
    },
    autocmds = {
        enableOnVimEnter = false,
        enableOnTabEnter = false,
        reloadOnColorSchemeChange = false,
    },
    mappings = {
        enabled = true,
        toggle = "<leader>zn",
    },
    buffers = {
        left = {
            bo = {
                filetype = "md",
            },
            scratchPad = {
                enabled = false,
                fileName = "notes",
                location = "~/",
            },
        },
        right = {
            enabled = false,
        },
    },
  })
end
return M
```

I'm missing something I believe. I added the flag to be true. #280 's issue is also still present. I'm not enabling this flag properly?

**Comment by shortcuts** [comment]
Hey! Thanks for testing, the option is at the root of the config, so it should be

```diff
-    options = {
-        fallbackOnBufferDelete = true,
-    },
+    fallbackOnBufferDelete = true,
```

**Comment by hqkhan** [comment]
No worries. I forgot to mention. That was the first thing I tried actually. 

```
local M = {
  "shortcuts/no-neck-pain.nvim",
  version = "*",
  -- "VeryLazy" hides splash screen
  event = "BufReadPre",
}

M.config = function()
  require("no-neck-pain").setup({
    fallbackOnBufferDelete = true,
    autocmds = {
        enableOnVimEnter = false,
        enableOnTabEnter = false,
        reloadOnColorSchemeChange = false,
    },
    mappings = {
        enabled = true,
        toggle = "<leader>zn",
    },
    buffers = {
        left = {
            bo = {
                filetype = "md",
            },
            scratchPad = {
                enabled = false,
                fileName = "notes",
                location = "~/",
            },
        },
        right = {
            enabled = false,
        },
    },
  })
end
return M
```

This resulted in the same behavior
