### ISSUE TITLE
[feat] Support nvim-neotest/neotest

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#246]
First of all, thank you for this awesome plugin! <3

## Describe the problem

When I open [neotest summary window](https://github.com/nvim-neotest/neotest#summary-window) with: `neotest.summary.toggle()` the no neck pain windows are closed. 

1. The initial state with no neck pain is on
<img width="1920" alt="default" src="https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/49fd8776-31b0-4337-8810-0cbfef4d61ac">

2. State after running `neotest.summary.toggle()` _(the no neck pain windows are hidden)_
<img width="1920" alt="open-neotest" src="https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/33370b0e-ea24-4db4-8dec-ba9908880846">

## Describe the solution

I would like to use one of the side windows, just like it works with nvim-tree so it would look something like:

<img width="1920" alt="desired" src="https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/a67ebade-ad12-4a23-99f0-2cc5c693d8aa">

**Comment by shortcuts** [comment]
Hey, thanks for the feedback 💓

I'm working on a way to support it in https://github.com/shortcuts/no-neck-pain.nvim/pull/247

**Comment by shortcuts** [comment]
hey, the last version should fully support neotest! don't hesitate to report bugs if you see any
