### ISSUE TITLE
Neotest configuration has no effect

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#251]
## Description

The neotest config has no effect. All the no-neck-pain windows are _still_ closed instead of using one of the side panels when i open the neotest summary.

related: https://github.com/shortcuts/no-neck-pain.nvim/issues/246

## Steps to reproduce

```lua
require("no-neck-pain").setup({
    width = 154,
    autocmds = {
        enableonvimenter = false,
    },
    mappings = {
        enabled = false,
    },
    integrations = {
        nvimtree = {
            position = "left",
            reopen = true,
        },
        undotree = {
            position = "left",
        },
        neotest = {
            position = "right",
            reopen = true,
        },
    },
})
```

## Expected behavior

No neck pain should one of the side panels when i open neotest summary

## Environment

- Neovim version: latest
- no-neck-pain.nvim 1.3.0
- Plugin clash: no neck pain

**Comment by shortcuts** [comment]
hey, thanks for reporting the issue! I indeed realized it, it's fixed in https://github.com/shortcuts/no-neck-pain.nvim/issues/251
