### ISSUE TITLE
Is it possible to center the commandline when using this plugin?

### ISSUE THREAD

**Issue by JetpackJackson** [shortcuts/no-neck-pain.nvim#253]
## Describe the problem

I've been using noice.nvim up until now, and I've been experimenting without it. However, when I have the buffers on, the commandline is still all the way at the bottom left side. I would like if it was in the middle under the middle buffer, but I don't know if this is possible and wanted to find out if it was.

![swappy-20231021-102148](https://github.com/shortcuts/no-neck-pain.nvim/assets/88674707/f64ecc9d-74bd-4fab-ab7e-82bf3b6c1fdf)

## Describe the solution

The commandline would be centered with the center buffer.

Thanks in advance for your help, and thanks for the awesome plugin!

**Comment by shortcuts** [comment]
Hey @JetpackJackson, thanks for opening the issue and the feedback!

Sorry but it's not possible to control the command line width with a plugin, buffers or windows etc. since (I assume) it's a reserved space by vim/neovim

**Comment by JetpackJackson** [comment]
Ah, ok, I figured it was probably going to be something like that (the reserved space I mean). Thanks again!
