### ISSUE TITLE
Feature request: Work with *neo-tree* inside *bufferline*

### ISSUE THREAD

**Issue by stevenxxiu** [shortcuts/no-neck-pain.nvim#260]
## Describe the problem

I use *neo-tree* inside *bufferline*.

*no-neck-pain* works great when I run it in a *bufferline* tab. However I can't use *neo-tree* while this is active.

- When I click the *neo-tree* panel, it immediately jumps back to the *bufferline* tab.
- If I use *smart-splits* to move left (`require('smart-splits').move_cursor_left`), I will be sent back to the *bufferline* tab after around 0.5s.

Relevant parts of my *bufferline* config:

```lua
return {
  'akinsho/bufferline.nvim',
  version = '*',
  dependencies = 'nvim-tree/nvim-web-devicons',
  opts = {
    options = {
      offsets = {
        {
          filetype = 'neo-tree',
          text = 'File Explorer',
          highlight = 'Directory',
          text_align = 'left',
        },
      },
    },
  },
}
```

Relevant parts of my *smart-splits* config:

```lua
return {
  'mrjones2014/smart-splits.nvim',
  keys = {
    { '<leader>h', function() require('smart-splits').move_cursor_left() end },
  },
}
```

## Describe the solution

It would be fantastic if I could use *neo-tree*, while my document is still centered by *no-neck-pain*.

**Comment by stevenxxiu** [comment]
Whoops this was an issue with my `'BufEnter'` callback.

**Comment by shortcuts** [comment]
thanks for finding the issue and fixing the discussion answer!
