### ISSUE TITLE
feature: allow `widthUp` value to be configurable

### ISSUE THREAD

**Issue by timtyrrell** [shortcuts/no-neck-pain.nvim#261]
## Describe the problem

5 is a tiny number

## Describe the solution

allow `widthUp` to be configurable

**Comment by shortcuts** [comment]
that's a great idea, gave it a shot here https://github.com/shortcuts/no-neck-pain.nvim/pull/264, not yet sure about the naming nor where it should live but definitely doable, don't hesitate to suggest

**Comment by shortcuts** [comment]
and thanks for using the plugin :D

**Comment by shortcuts** [comment]
Niceeeee thanks for all the feature requests!
