### ISSUE TITLE
feature: add command to open with right buffer aligned

### ISSUE THREAD

**Issue by timtyrrell** [shortcuts/no-neck-pain.nvim#262]
## Describe the problem

Based on whether someone is using a small screen or a large screen, they might want a different buffer alignment

## Describe the solution

1. Add a command like `NoNeckPainRightEnabled`
2. Add a command allow the passing in of different config values

**Comment by shortcuts** [comment]
Hey, thanks for the suggestion and using the plugin :D 

Could you please provide more information on what you'd expect from this command? is it to have a way to toggle a side buffer on and off? if so, that's a great idea!

**Comment by timtyrrell** [comment]
Tested out, and serves my needs, thanks again! 👍

**Comment by shortcuts** [comment]
Lovely!!
