### ISSUE TITLE
Tab switching while NoNeckPain is enabled issue

### ISSUE THREAD

**Issue by timtyrrell** [shortcuts/no-neck-pain.nvim#273]
## Description

(sorry, this is a bit confusing, but the reproduction steps should be clear)
If you switch to the first tab from a second tab, while NoNeckPain is enabled on this second tab, the plugin gets confused about the state of that second tab. 

I am not able to duplicate this in the reverse order, meaning if I have NoNeckPain enabled on the first tab, then switch to the second tab, and then back to the first tab, the plugin state seems to be remembered on the first tab.

## Steps to reproduce

1. open a file in neovim
2. open a file in a second tab
3. run `:NoNeckPain` in the second tab
4. switch to the first tab `gT`
5. switch back to the second tab `gt`
6. run `:NoNeckPain` in the second tab and see the view shrink further instead of expanding

## Expected behavior

the plugin state for each tab is remembered

## Environment

- Neovim version: [e.g. 0.5.x / 0.6.x / 0.7.x / 0.8.x / Nightly]
- no-neck-pain.nvim version: [e.g. latest / 0.1.2 / dev]
- Plugin clash: [e.g. Telescope float window / lsp diagnostic]

**Comment by shortcuts** [comment]
thanks a lot for the suggestion again!! it even helped finding **AN OTHER** bug! I don't often work with tabs so I did not really tested it, sorry D:

**Comment by shortcuts** [comment]
released in 1.6.3!

**Comment by timtyrrell** [comment]
Much better, thanks! I will let you know if I see anything else.

**Comment by shortcuts** [comment]
Thanks for all the reports! Enjoy the plugin and thanks for using it :D
