### ISSUE TITLE
NoNeckPain's buffer is not visible when using nvim, though it might be opened, just not visible?

### ISSUE THREAD

**Issue by vinoff** [shortcuts/no-neck-pain.nvim#278]
This is my NoNeckPain config:

```
return {
	"shortcuts/no-neck-pain.nvim",
	config = function()
		require("no-neck-pain").setup({
			autocmds = {
				enableOnVimEnter = true,
				-- enableOnVimEnter = false,
			},
			buffers = {
				colors = {
					background = "#000000",
				},
				right = {
					enabled = false,
				},
			},
		})
	end,
}
```

When using Neovide,  it opens at startup. However, using nvim in the terminal, the buffer is not visible. It's as if it is not opening at startup. HOWEVER, if I do `:NoNeckPain`, the buffer does NOT open. If I do `:NoNeckPain` again (a second time) it DOES open. So, in sum, I have to do `:NoNeckPain` twice, which suggests that NoNeckPain is actually opened at startup, just not visible?

What could be happening here? How can I further debug this?

**Comment by shortcuts** [comment]
Hey, thanks for using the plugin and reporting the issue! I believe there indeed some support to be added on the NNP side to properly boot with Neovide, I'll try to reproduce ASAP!

**Comment by vinoff** [comment]
I think you misunderstood @shortcuts. The problem is with Nvim in terminal, not with Neovide. It works fine with Neovide.

**Comment by shortcuts** [comment]
Hey, sorry for coming back late to this, I just remembered the issue!

Would you mind sharing a screenshot of you setup? I assume there is not enough space to have the buffers opened, however the second time it shouldn't open then 🤔

**Comment by vinoff** [comment]
Hey @shortcuts.

There is space. The setup is exactly the same as Neovide. They run from exactly the same config file. The only difference is the font used. The setup is just 1 window, 2 if NoNeckPain is opened. I shared a screenshot of my setup here: https://github.com/shortcuts/no-neck-pain.nvim/issues/277. For neovim terminal it is the same.

So,  to sum it up:

Neovide:
- It opens by default;

Neovim terminal:
- Doesn't open by default;
- Have to call NoNeckPain TWICE to have it opened.

**Comment by vinoff** [comment]
It seems to have to do with my terminal, somehow. 

Neovim terminal in Wezterm does NOT open NNP by default.
Neovim terminal in xfce terminal opens NNP by default.

**Comment by shortcuts** [comment]
> It seems to have to do with my terminal, somehow.
> 
> Neovim terminal in Wezterm does NOT open NNP by default. Neovim terminal in xfce terminal opens NNP by default.
> 
> EDIT:
> 
> Some more testing.
> 
> Font size (works or not):
> 
> * 10 (YES)
> * 12 (NO)
> * 14 (NO)
> * 15 (YES)
> * 16 (YES)
> 
> What do you think is happening?

Thanks a lot for the explanations! I assume that it is due to how we compute column width. Maybe you can try to see if with font 12 the column width differ weirdly when calling `:lua vim.print(vim.api.nvim_list_uis()[1].width)`. I assume something is weirdly rendered, I can try to provide a fallback in that case or a `force` mode 🤔 

I'll try to install Wezterm and reproduce myself for easier debugging
