### ISSUE TITLE
Integration with Trouble

### ISSUE THREAD

**Issue by aabbccddeeffggj** [shortcuts/no-neck-pain.nvim#279]
## Describe the problem

Hi, firstly, thanks for the awesome plugin. 
There's a plugin called "Trouble", from folke, which basically toggles a window in the bottom for diagnostics, and other things one might implement for oneself.
I realized that toggling on your plugin's mode with both my main window and the Trouble's one active makes them fit correctly in the middle of the screen, but once I toggle off Trouble and them toggle it on again, Trouble takes all the width of my neovim. 
## Describe the solution

I assume it's within the realm of possibilities, but unsure of how Trouble handle its window.

Thanks

**Comment by shortcuts** [comment]
Hey! Thanks for reporting and using the plugin :D!

> I assume it's within the realm of possibilities, but unsure of how Trouble handle its window.

usually those windows are implemented to be "relative" (floating), I might've missed a check somewhere, I'll take a look asap!

**Comment by aabbccddeeffggj** [comment]
Thanks a lot for your efforts!

**Comment by shortcuts** [comment]
Hey, I've took a look at how it behaves and it seems pretty correct to me. My guess would be either because they are readonly windows or because they have fixed width/height. IIRC help pages behaves similarly, I'll check to see if there's a way to tweak that

**Comment by aabbccddeeffggj** [comment]
I see, thanks! Once you have an update on whether it's possible or not please tell me.

**Comment by shortcuts** [comment]
Hey @aabbccddeeffggj, I just tried with the new v3 version and trouble seems to work out of the box! Let me know if you notice any issue, feel free to reopen :)
