### ISSUE TITLE
Opening new buffer after "NoNeckPain" causes line numbers to disappear

### ISSUE THREAD

**Issue by hqkhan** [shortcuts/no-neck-pain.nvim#280]
## Description

After closing `NoNeckPain` "mode", the next buffer has no line numbers at all. 

## Steps to reproduce

1. Open some files
2. Issue `:NoNeckPain`
3. Close buffer (two times since the first time, it'll go to `[No Name]` buffer)
4. Open another file

I tested without issuing `NoNeckPain` and this does not occur.

## Expected behavior

Once buffer with `NoNeckPain` is closed, neovim goes back to "normal". Opening new buffers should have line numbers or relative line numbers.

## Environment

- Neovim version: NVIM v0.9.2
- no-neck-pain.nvim version: latest
- Plugin clash: None

**Comment by shortcuts** [comment]
Hey @hqkhan, thanks for reporting! I can confirm this is indeed an issue and I believe it is linked to https://github.com/shortcuts/no-neck-pain.nvim/issues/243 as well. Can you confirm you use the `:bd` or `:bdelete` command to close the buffer?

**Comment by shortcuts** [comment]
and as always, thanks for using the plugin! <3

**Comment by hqkhan** [comment]
Hi @shortcuts, thank you for your response!

>Can you confirm you use the :bd or :bdelete command to close the buffer?

I have a mapping to delete buffer, here it is:
```
map('n', '<leader>bd', '<Esc>:bd<CR>',
  { silent = true, desc = "Close current buffer" })
```

**Comment by jfab20** [comment]
@shortcuts Hello! Thanks for the responses. With the new option ```fallbackOnBufferDelete=true``` , the buffer now seems to close (and leave an empty buffer) correctly. 

However I have found even with the option enabled that this issue of line numbers is still not fixed, right? 

Also I don't know why but whenever I use ```:bd``` and then open a new file, the new file not only doens't have line numbers but has a darker font? It's hard to explain so here is a picture

Opening a file without before buffer delete:
![image](https://github.com/shortcuts/no-neck-pain.nvim/assets/81712003/58c65d8f-4c99-4d9a-b007-85548340c11b)


Opening a file after deleting a buffer:
![image](https://github.com/shortcuts/no-neck-pain.nvim/assets/81712003/89a834f2-2aca-4362-93ef-cd1a3d8bbfe4)


You can see that the text which is not highlighted is darker..

**Comment by shortcuts** [comment]
Hey @jfab20 thanks for using the plugin and reporting the issue! I converted your comment to an issue here https://github.com/shortcuts/no-neck-pain.nvim/issues/286 and can confirm there is indeed a bug

I found the solution, will provide a fix asap!
