### ISSUE TITLE
Change WinSeparator highlight group when on vertical split.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [shortcuts/no-neck-pain.nvim#282]
## Describe the problem

Hi, there is this detail in the right side of my neovim narrowed window which bothers me:
![image](https://github.com/shortcuts/no-neck-pain.nvim/assets/133555950/bc5c4792-5b39-444e-9263-fcb878b31734)
When I change the highlight of the WinSeparator with this command: 
`winhighlight=WinSeparator:NoNeckBg` (NoNeckBg is a highlight I defined to match with the NoNeckPain windows background)
I can successfully get ride of this line, but unfortunately I'm left with a way too "rough" window separator
![image](https://github.com/shortcuts/no-neck-pain.nvim/assets/133555950/de4e0809-7374-4245-b3a0-141108487312)

## Describe the solution
Define highlight groups for two distinct situations:
1. No vertical split between the working windows: Define highlight to blend the WinSeparator group with the NoNeckPain background window.
2. Existence of vertical split between the working windows: Leave the default highlight of the WinSeparator group.

Maybe there's a more optimal solution for this, since the horizontal splits will not work very well, but that's what I have in mind for now. Thanks.

**Comment by polirritmico** [comment]
Try `:lua vim.api.nvim_set_hl(0, "WinSeparator", { fg = 1250067 })`. It's working for me.

**Comment by polirritmico** [comment]
So, if I'm correctly understanding, you have two states, one with NNP enabled that works fine with your highlights and one with windows splits that have that "huge gap" that you want to get rid of?

If so, I would go with a different approach and change the highlights when NNP is enabled and revert them when is disabled:

```lua
require("no-neck-pain").setup({
    -- your setup...
})

NoNeckPain_default_border_hl = {}
NoNeckPainToggleState = false

local NNP_toggle_with_custom_border_hl = function()
    local border_name = "WinSeparator"
    local custom_hl = { fg = "#131313" } -- or any color you like

    if NoNeckPain_default_border_hl.fg == nil then
        NoNeckPain_default_border_hl = vim.api.nvim_get_hl(
            0, { name = border_name, link = true }
        )
    end

    if NoNeckPainToggleState then
        vim.api.nvim_set_hl(0, border_name, NoNeckPain_default_border_hl)
    else
        vim.api.nvim_set_hl(0, border_name, custom_hl)
    end
    NoNeckPainToggleState = not NoNeckPainToggleState

    vim.cmd([[NoNeckPain]])
end

-- mapping
vim.keymap.set({"n"}, "<leader>tc", NNP_toggle_with_custom_border_hl, {silent=true})
```

**Comment by aabbccddeeffggj** [comment]
Hi, in both screenshots I'm using the no-neck-separator layout.

**Comment by shortcuts** [comment]
Hey @aabbccddeeffggj, thanks for using the plugin and reporting the issue, thanks @polirritmico for the help, much appreciated! ❤️ 

If you believe there is next step applicable for the default highlight groups of the plugin don't hesitate to suggest/open a pr, I'll more than happy to help :)
