### ISSUE TITLE
Wrong background color after resize

### ISSUE THREAD

**Issue by kiryph** [shortcuts/no-neck-pain.nvim#285]
## Description

When I resize the nvim-qt window from wide to tall and back to wide, the background color of the side buffers are incorrect.

## Steps to reproduce

1. Start nvim-qt on a 16:9 screen, I get the expected result:
![Screenshot 2023-12-18 at 08 09 59](https://github.com/shortcuts/no-neck-pain.nvim/assets/371756/466b9d4e-4bbd-42cf-b7e2-60acd05603a5)

3. Then I open a second nvim-qt window using the window tiling manager Yabai on macOS:
![Screenshot 2023-12-18 at 08 11 19](https://github.com/shortcuts/no-neck-pain.nvim/assets/371756/439ad496-99b3-447b-89b9-d5696c655b05)

4. Then I close one, and the other one is resized to full screen again and no-neck-pain adds correctly again the side buffers but with the incorrect background color:
![Screenshot 2023-12-18 at 08 12 11](https://github.com/shortcuts/no-neck-pain.nvim/assets/371756/d0c8ec5b-e233-44f0-8b0d-a940e6609835)

I can fix it by calling `:color github_light`. Toggling twice no neck pain, does not fix it.

## Expected behavior

The same as in the first picture.

## Environment

- Neovim version: 0.9.4
- no-neck-pain.nvim version: 1.7.0 (stable, commit baf3ef)
- Color scheme: https://github.com/projekt0n/github-nvim-theme variant github_light
- Plugin clash: unclear (using kickstart.nvim with a few additions)

Plugin manager Lazy.nvim:

```lua
return {
  "shortcuts/no-neck-pain.nvim",
  version = "*",
  config = function()
    require("no-neck-pain").setup({
      debug = false,
      -- The width of the focused window that will be centered. When the
      -- terminal width is less than the `width` option, the side buffers won't
      -- be created.
      --- @type integer|"textwidth"|"colorcolumn"
      width = 120,
      autocmds = {
        -- When `true`, enables the plugin when you start Neovim.
        -- If the main window is  a side tree (e.g. NvimTree) or a
        -- dashboard, the command is delayed until it finds a valid window.
        -- The command is cleaned once it has successfuly ran once.
        --- @type boolean
        enableOnVimEnter = true,
        -- When `true`, enables the plugin when you enter a new Tab.
        -- note: it does not trigger if you come back to an existing tab,
        -- to prevent unwanted interfer with user's decisions.
        --- @type boolean
        enableOnTabEnter = true,
        -- When `true`, reloads the plugin configuration after a colorscheme change.
        --- @type boolean
        reloadOnColorSchemeChange = false,
      },
    })
  end
}
```

**Comment by shortcuts** [comment]
Hey, thanks for reporting and using the plugin! I'll take a look asap, I assume there's a link with https://github.com/shortcuts/no-neck-pain.nvim/pull/283

**Comment by shortcuts** [comment]
Bug confirmed and it was there before some rewrites, taking a look for a fix

**Comment by shortcuts** [comment]
Actually this is not a bug if the reproductions step I tried are correct, can you please confirm you do something like:
1. Open nvim with NNP enabled at startup
2. Change color scheme
3. Reduce window size to close side buffers
4. Restore window size to re-open side buffers
5. Side buffers have the wrong background color

If you set `autocmds.reloadOnColorSchemeChange` to `true`, the side buffers in step 5 have the correct color

---

Feel free to reopen if you still observe the issue!

**Comment by kiryph** [comment]
> If you set autocmds.reloadOnColorSchemeChange to true, the side buffers in step 5 have the correct color

Yes, that actually has resolved it. Thanks.

Maybe the description or even the name could reflect its wider use than just color scheme changes.

**Comment by shortcuts** [comment]
> > If you set autocmds.reloadOnColorSchemeChange to true, the side buffers in step 5 have the correct color
> 
> Yes, that actually has resolved it. Thanks.
> 
> Maybe the description or even the name could reflect its wider use than just color scheme changes.

Thanks for the suggestion, indeed the scope is broader than what the name implies, I'll look at it for the next major!
