### ISSUE TITLE
Disable this when *diffview* is activated

### ISSUE THREAD

**Issue by stevenxxiu** [shortcuts/no-neck-pain.nvim#289]
## Description

When *diffview* is activated between 2 *Markdown* files. I run into all sorts of issues.

- When I scroll down in the *Markdown* file, many parts of the file gets folded, I think by the *vim-markdown* plugin I have.
- The option `enhanced_diff_hl` in *diffview* stops coloring regions red, but with *no-neck-pain* activated, they turn red again.

I tried to run `NoNeckPain.disable()` when I see the `DiffviewFiles` file type, but this gave me endless errors in the messages.

## Steps to reproduce

1. Install [Neogit](https://github.com/NeogitOrg/neogit), [diffview](https://github.com/sindrets/diffview.nvim).
1. Enable `enhanced_diff_hl` in *diffview*.
2. Run `:Neogit` in a repo with a *Markdown* file. Press `d` on the file. Then `d` again to view changes.
3. Move right to go in a *Markdown* file buffer.
4. The described errors occur.

## Expected behavior

None of the described errors occur.

## Environment

- Neovim version: 0.9.4
- no-neck-pain.nvim version: 1.7.1
- Plugin clash:

**Comment by shortcuts** [comment]
Hey, thanks for reporting the issue and using the plugin!

I did not managed to reproduce the issue, could you please share screenshots of the no-neck-pain error that occurs?

**Comment by stevenxxiu** [comment]
Hey sorry about this one. It was late last night and I was a bit frustrated. It was an issue on my end. 😅
