### ISSUE TITLE
[feature] add support for Symbols Outline

### ISSUE THREAD

**Issue by embe221ed** [shortcuts/no-neck-pain.nvim#296]
## Describe the problem

the NvimTree support is a pretty good feature, I would like to ask for a similar feature for [Outline](https://github.com/hedyhli/outline.nvim) plugin.

## Describe the solution

Implement similar solution as it is done for NvimTree.

**Comment by shortcuts** [comment]
Hey @embe221ed thanks for submitting the request :D 

I'll take a look once I'm back from my paternity leave, in the meantime if you'd like to add support for it, you can take a look at the hint comment I've put here https://github.com/shortcuts/no-neck-pain.nvim/issues/297#issuecomment-1925463898

**Comment by embe221ed** [comment]
hey @shortcuts!

I'll take a look at the hint comment and will try to implement the feature by myself, thanks!

**Comment by shortcuts** [comment]
Hey, this will be supported in 1.12.0 :)
