### ISSUE TITLE
Show opened tabs/buffers in NNP.

### ISSUE THREAD

**Issue by vinoff** [shortcuts/no-neck-pain.nvim#303]
I would like to use NoNeckPain as a "tab bar" of sorts. Basically, I have removed the top bar that showed opened tabs (barbar) and would like those tabs to be showed in NNP instead. Would this be in scope for this project?

This would be optional, with a tag "show_opened_buffers = true/false". Then, opened buffers/tabs would be shown in the NNP window, as well as the selected (currently being viewed) buffer/tab.

**Comment by shortcuts** [comment]
Hey @vinoff thanks for using the plugin and for your suggestion! 

This seems related to https://github.com/shortcuts/no-neck-pain.nvim/issues/209, indeed it would be great to be able to let the user select different sources e.g. buffer selector as you proposed, I'll see how feasible it is!

**Comment by shortcuts** [comment]
(I'm closing this one in favour of https://github.com/shortcuts/no-neck-pain.nvim/issues/209, feel free to continue the discussion there!)
