### ISSUE TITLE
[feature] Option to keep the cursor out of the panel/s

### ISSUE THREAD

**Issue by chelsea6502** [shortcuts/no-neck-pain.nvim#306]
Hello! My neck and I thank you for making such a great plugin.

I use NNP with one left panel and no right panel. I purely use it for padding and nothing else.

I find myself in situations where cursor enters inside the panel when I want it to be on the file I have opened. An example is in the ChatGPT.nvim plugin, where leaving a chat with CTRL+C sends the cursor inside the left panel.

Basically, **I'd love to see an option flag to ensure the cursor never enters the panel.** I'm not interested in any scratchpad capability, so I'd like to just have it outside no matter what.

I imagine something like this is doable with autocmds for the time being, but I'm unfamiliar with how to do it. If anyone knows of a reliable/stable way to do it with autocmds, let me know.

**Comment by shortcuts** [comment]
Hey! Thanks for using the plugin and I'm glad you like it!!

Indeed it might be possible to provide such option, I believe we can either:
- force a refocus on the `curr` (centered) buffer
- refocus the last focused buffer

I'm not sure what's best but both solutions have similar implementation so maybe I can provide both

**Comment by shortcuts** [comment]
Actually the best option would be to jump to the next available buffer, skipping the padding one, but I'm not yet sure if doable

**Comment by shortcuts** [comment]
Thanks for the awesome suggestion, it was actually not that hard to implement and pretty straight forward!

The feature will be available in the `1.10.0` version, and you can enable it with the following config

```lua
return {
    {
        "shortcuts/no-neck-pain.nvim",
        lazy = false,
        dev = true,
        opts = {
            autocmds = {
                skipEnteringNoNeckPainBuffer = true,
            },
        },
    },
}
```

**Comment by chelsea6502** [comment]
Fantastic!! Thank you so much!

**Comment by sand4rt** [comment]
Just tested it and it works great, thank you! The only thing i noticed is that cursor is placed in the NNP buffer before it moves to the correct window which causes flickering:

https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/a440e5bf-d6f7-439c-aaa0-2121c2779efe

**Comment by shortcuts** [comment]
Hey @sand4rt thanks for testing the feature already!

Here I've decided to leverage `WinEnter` to determine if we should re-route the cursor, this is has the downside of waiting for a cursor to enter a win before re-routing but offers a reliable way as we don't have to listen to the user input (which can be misinterpreted) nor add overhead to the plugin

Looking at the events [WinEnter](https://neovim.io/doc/user/autocmd.html#WinEnter) seems to be the way to go, however I can take a look at [WinLeave](https://neovim.io/doc/user/autocmd.html#WinLeave) or [BufLeave](https://neovim.io/doc/user/autocmd.html#BufLeave) provides enough information (targeted window) to see if we can "predict" where to re-route

**Comment by shortcuts** [comment]
released https://github.com/shortcuts/no-neck-pain.nvim/pull/322 in 1.10.1 which provides some improvements! flickering is still there sadly :(

**Comment by sand4rt** [comment]
Awesome! I was looking into this as well, I found `vim.api.nvim_win_set_config(win, { focusable = true })` but that only seems to work for floating windows :(
