### ISSUE TITLE
Issue when used with alpha-nvim

### ISSUE THREAD

**Issue by vincentlabelle** [shortcuts/no-neck-pain.nvim#314]
## Description

When NNP is triggered via `enableOnVimEnter` and I open neovim on my dashboard styled greeter made with [alpha-nvim](https://github.com/goolord/alpha-nvim), the whole dashboard is slightly off center. Then, if I proceed to a file from the dashboard, everything is centered properly except the autocomplete menu. Strangely, if prior to proceeding to a file, I move the cursor (on the dashboard) it brings everything back to the center (and I don't have any issues when proceeding to a file).

If I open vim on a file or folder, there is no issue.

Thanks for the amazing plugin! :+1: 

## Steps to reproduce

I am only able to reproduce on a wide screen (i.e., 34"), and I don't have the issue otherwise.

1. Set `enableOnVimEnter` to `true`
2. Setup a dashboard greeter with alpha-nvim
3. Open the dashboard

## Expected behavior

Everything is centered properly when opening the greeter, or the NNP trigger is disabled until the next buffer. It might be possible to solve this using a similar approach to https://github.com/shortcuts/no-neck-pain.nvim/issues/17?

## Environment

- Neovim version: 0.9.5
- no-neck-pain.nvim version: 1.8.1
- Plugin clash: alpha-nvim

**Comment by shortcuts** [comment]
Hey @vincentlabelle, thanks for reporting the issue and I'm glad you like the plugin!!

I've tried reproducing it but so far no luck (I'm on no-neck-pain latest version, 1.8.3), I've joined a recording so you can let me know if you have a different config/do different input


https://github.com/shortcuts/no-neck-pain.nvim/assets/20689156/690270db-bea0-49e8-8708-d24311e14542

**Comment by vincentlabelle** [comment]
Hey @shortcuts, thanks for looking into the issue!

I don't see anything from the video in terms of config/input that could be the cause of the discrepancy. I use the dashboard theme of alpha rather than the startify theme, but I doubt that's relevant.

I've tried updating to version 1.8.3, but I still have the issue.

I've taken two videos to show how I get the issue on a 34" screen with an aspect ratio of 21:9, but I don't get the issue on a 32" screen with an aspect ratio of 16:9. I hope this can help troubleshoot.


https://github.com/shortcuts/no-neck-pain.nvim/assets/40727826/0f50eb5f-108e-42bf-aab9-dccbd5a47e73


https://github.com/shortcuts/no-neck-pain.nvim/assets/40727826/e4024388-6745-41cd-88b6-c650d0100937

**Comment by shortcuts** [comment]
Thanks a lot @vincentlabelle for the throughout reproduction, I don't have such screen at home so can't really reproduce but looking at the videos my guess is that https://github.com/shortcuts/no-neck-pain.nvim/pull/317 will fix it. Do you have a way to try the fix by installing this specific branch? e.g. if you use lazy.nvim you can do:
```lua
return {
    "shortcuts/no-neck-pain.nvim",
    branch = "feat/support-alpha",
    ....
}
```

**Comment by vincentlabelle** [comment]
Thanks @shortcuts for being so responsive! I tested #317, and it fixes the issue. 😄

**Comment by shortcuts** [comment]
> Thanks @shortcuts for being so responsive! I tested #317, and it fixes the issue. 😄 

Nice to hear!! Thanks for testing and using the plugin :D
