### ISSUE TITLE
feat: top and bottom windows

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#340]
## Describe the problem

Thanks again for the plugin :) I found a slight inconvenience with bottom and top buffers/windows; 

https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/396764a6-c93e-4136-a39d-ce2b6cb7ffbc

1. open a top or bottom buffer _(e.g. fugitive, trouble or quick-fix list)_
2. open a side buffer _(e.g. neotree)_
3. close the side buffer _(e.g. neotree)_

## Describe the solution

The bottom or top buffer should take its full width again when the side buffer is closed. Maybe with?:

```lua
opts = {
        integrations = {
            NeoTree = {
                position = "left",
            },
            fugitive = {
                position = "top", -- or bottom
            },
        },
    }  
}
```

**Comment by shortcuts** [comment]
Thanks for reporting @sand4rt and discovering all of those issues ahah

I also noticed that, even `copen` behaves this way, I'm currently trying to find the root cause of this!

**Comment by shortcuts** [comment]
Hey! So I've found the issue, turns out it's a bit more complicated than expected to fix but still in progress
