### ISSUE TITLE
Unable to move the cursor to the main buffer when `skipEnteringNoNeckPainBuffer = true`

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#353]
## Steps to reproduce

1. set `skipEnteringNoNeckPainBuffer = true`
2. open 2 buffers above the main buffer
3. try to navigate to the main buffer

It doesn't allow the cursor to move to the main buffer.

<img width="1919" alt="Screenshot 2024-05-18 at 20 58 06" src="https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/8f1dd4ba-91ca-497b-b78f-62f60f2b0d22">

## Expected behavior

To move the cursor to the main buffer.

## Environment

- Neovim version: [0.10]
- no-neck-pain.nvim version: [latest]

**Comment by shortcuts** [comment]
hey @sand4rt thanks for keeping up with the plugin and finding this new issue :) that's super weird I use this daily and never encountered it, will try to reproduce asap!

**Comment by sand4rt** [comment]
No rush!:) It only happens when there are 2 buffers on top btw
