### ISSUE TITLE
Is it possible to make NNP **unfocusable**?

### ISSUE THREAD

**Issue by vinoff** [shortcuts/no-neck-pain.nvim#369]
For my use case, it would be nice if NNP is unfocusable. For example, sometimes I have a floating window from another plugin and, after closing that floating window, instead of having the main file focused, I have the NNP focused, which is annoying. I then have to switch to the main window.

I would love if NNP had an option "preventFromBeingFocused = True/False", that could prevent it from it ever being focused.

**Comment by shortcuts** [comment]
Hey! Thanks for using the plugin :D It looks like you are looking for https://github.com/shortcuts/no-neck-pain.nvim/discussions/341#discussioncomment-9002712, no?

**Comment by vinoff** [comment]
> Hey! Thanks for using the plugin :D It looks like you are looking for [#341 (comment)](https://github.com/shortcuts/no-neck-pain.nvim/discussions/341#discussioncomment-9002712), no?

Yes! Thank you!
