### ISSUE TITLE
no-neck-pain exits neovim when closing a tab page with no-neck-pane enabled

### ISSUE THREAD

**Issue by lorentzforces** [shortcuts/no-neck-pain.nvim#370]
## Description

If one opens another tab page, enables no-neck-pane on that tab page, and then closes the window in that tab (via `:q` for example), neovim exits.

## Steps to reproduce

1. Start neovim with `no-neck-pain.nvim` loaded
2. Open another tab
3. Enable no-neck-pain in that tab
4. Close the buffer in this tab
5. Neovim quits entirely (with exit code 0)

## Expected behavior

I would expect the current tab page to close, given that the only "non-no-neck-pain" window in the tab page has closed. The entire editor quitting is unexpected.

## Environment

- Neovim version: `0.10.0`
- no-neck-pain.nvim version: tested with latest
- Plugin clash: no other plugins loaded

I have created [a repo that will create a docker image with a minimal reproduction setup.](https://github.com/lorentzforces/no-neck-pain-repro) Reference as needed for a built setup, or just for a concrete series of actions which result in the observed behavior.

Happy to perform additional troubleshooting on request.

While I'm here, also just want to share that I love this plugin. I frequently have single buffers open (and am a stickler for limiting line lengths in my code), and really like being able to center what I'm looking at.

**Comment by shortcuts** [comment]
Hey @lorentzforces, thanks for using the plugin and the super detailed reproduction!!

I can confirm I'm able to reproduce the issue, I'll try to find a solution!

**Comment by lorentzforces** [comment]
Amazing, thank you for the fix, and thanks again for a great plugin.
