### ISSUE TITLE
[bug] Not behaving correctly when we have split windows

### ISSUE THREAD

**Issue by MuhametSmaili** [shortcuts/no-neck-pain.nvim#396]
## Description

**Okay, functionality:**

If you have open one buffer only, then you active noNeckPain everything seems okay.
![image](https://github.com/user-attachments/assets/83429ba5-5bf2-439e-ba21-2fdabb70d5f3)

If we decide to split this buffer into two buffers, again the functionality is the same as it always was
![image](https://github.com/user-attachments/assets/f0354b02-42c2-4644-89da-bdfa208bf76b)

**Problems:**

Now let's assume we toggle off the no neck pain, we go back to the two buffers into the split (works okay), but now activating the NoNeckPain again doesn't split correctly, it cuts one of the buffers (check image)
![image](https://github.com/user-attachments/assets/077ed5e2-121c-4b27-9ae3-f6f68cf0d1f7)

This also happens if we activate the noNeckPain for the first time on split mode. 

## Steps to reproduce

- Open a buffer
- Open a split (ctrl + w v)
- Active the NoNeckPain

## Expected behavior

The expected behavior is to center both splits into the described width of the buffer. (same as the second image above)

## Environment

- Neovim version: Nightly & 10
- no-neck-pain.nvim version: latest
- Plugin clash:

**Comment by MuhametSmaili** [comment]
For now, I have downgraded to version `2.0.0` which seems to work fine

**Comment by shortcuts** [comment]
Hey sorry I totally forgot to answer! Thanks a lot for opening the issue and using the plugin :)

It was a mistake on my side, I should pre-compute the width instead of waiting for the window to be created

Should be fixed in 2.0.3!
