### ISSUE TITLE
[bug]: Incorrect side buffer sizes on 2 or more `tabnew`s

### ISSUE THREAD

**Issue by MayRedwood** [shortcuts/no-neck-pain.nvim#399]
### Description

Upon opening a tab and running `:NoNeckPain<cr>`, the plugin works as expected, with the `width` configuration option being respected. However, if you close the tab and open a new one, the plugin behaves incorrectly, with the side buffers taking a very large portion of the screen. This also happens with the `enableOnTabEnter` autocommand. Below is my lazy.nvim config.
```lua
  {
    'shortcuts/no-neck-pain.nvim',
    lazy = false,
    opts = {
      width = 128,
      debug = true,
      autocmds = {
        -- enableOnVimEnter = true,
        -- enableOnTabEnter = true,
        reloadOnColorSchemeChange = true,
      },
      buffers = {
        -- right = {
        --   enabled = false,
        -- },
        -- scratchPad = {
        --   enabled = true,
        --   pathToFile = '~/Documents/np.norg',
        -- },
      },
      mappings = {
        enabled = true,
        toggle = '|',
      },
    },
  }
```

### Neovim version

0.10.x

### Steps to reproduce

1. Enter Neovim
2. Run `:tabnew<cr>`
3. Run `:NoNeckPain<cr>`, the plugin should work as expected
![image](https://github.com/user-attachments/assets/3a8d0b72-af2d-4e0d-bfe5-9e6f5427b8c1)
4. Run `:tabc<cr>`, then `:tabnew<cr>` again
5. Run`:NoNeckPain<cr>`: the plugin does not work as expected
![image](https://github.com/user-attachments/assets/99d1ed37-1492-48ba-9a85-41e349f4b39a)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by shortcuts** [comment]
Hello, thanks for using the plugin and reporting the issue! I can confirm it is not an expected behavior, working on a fix!

**Comment by shortcuts** [comment]
2.0.5 will contain the fix :)
