### ISSUE TITLE
barbar.nvim integration

### ISSUE THREAD

**Issue by Kamyil** [shortcuts/no-neck-pain.nvim#403]
## Describe the problem

Wondering if it would be possible to add `barbar.nvim` integration (or maybe rather barbar should add NoNeckPain integration). So far for me it's the best tab plugin and having integration with it would be purely match made in heaven. 

![image](https://github.com/user-attachments/assets/2831eb9b-d049-455a-99d9-852160b5b6a3)

## Describe the solution
The only thing such integration would really need is to let barbar respect the offset that NoNeckPain side buffers apply, so tabs would be centered rather than stretched to beginning and end of the window

I know that barbar offers offset functionality
https://github.com/romgrk/barbar.nvim?tab=readme-ov-file#offset-bufferline-when-showing-sidebars
but it seems to be mainly focused on sidebars

Generally, just checking if it would be possible or should I rather create a feature request for barbar.nvim

Thank you once again!

**Comment by shortcuts** [comment]
Hey @Kamyil thanks for opening the issue

This request is out of scope of this plugin, we are not able to control how barbar sets their width so it would be better if the feature request was on their side.

Alternatively, you can use a global status line, which would only display information about the currently focused buffer (this is what I use personally, with barbar too)

**Comment by Kamyil** [comment]
Hi! Thank you for the response
I will reach to barbar maintainers then

Have a nice day!

**Comment by Kamyil** [comment]
https://github.com/romgrk/barbar.nvim/issues/618#issuecomment-2387704122
They responded and their solution works. Solution is in ^this  comment
