### ISSUE TITLE
I can't see what Integrations are supposed to do?

### ISSUE THREAD

**Issue by fakeharxy** [shortcuts/no-neck-pain.nvim#426]
Sorry for the blank issue - I was not sure where to file this:

I'm just not sure what the integrations config is supposed to do. I use undo tree and have set this in my no-neck-pain setup:

```
  integrations = {
    undotree = {
      position = "left",
    },
  },
```

but whether I set it to 'left' or 'right' makes no difference - I can't see how it's affecting no-neck-pain at all? It just pops up in a new pane to the far left, on the left hand side of my no-neck-pain buffer.

Could something be added to the docs or showcase maybe about what we're trying to achieve with integrations?

**Comment by shortcuts** [comment]
Hey, thanks for using the plugin :)

> Sorry for the blank issue - I was not sure where to file this:

No worries, but https://github.com/shortcuts/no-neck-pain.nvim/discussions are made for this purpose

> I'm just not sure what the integrations config is supposed to do. I use undo tree and have set this in my no-neck-pain setup:
> 
> ```
>   integrations = {
>     undotree = {
>       position = "left",
>     },
>   },
> ```

It is just here to hints the plugin so when scanning the window layout, we know from which side we should subtract the width of the integration. So for example, if you were supposed to have a padding of 100 columns on each side, but undotree takes 42, only 58 will be added so your layout is still centered.

**Comment by shortcuts** [comment]
> Could something be added to the docs or showcase maybe about what we're trying to achieve with integrations?

Good point, added here https://github.com/shortcuts/no-neck-pain.nvim/pull/427

**Comment by fakeharxy** [comment]
Ahhh I seeeee. This might be just me, but I'd love a `left-side-position: "right"` so that undotree (or whatever) moves to the right side of the 'left' no-neck-pain buffer. But this is very specific! Great work on the plugin.

**Comment by shortcuts** [comment]
> Ahhh I seeeee. This might be just me, but I'd love a `left-side-position: "right"` so that undotree (or whatever) moves to the right side of the 'left' no-neck-pain buffer. But this is very specific! Great work on the plugin.

I see!!!!!!! It could be a great feature actually but quite unsure how I can bend the current logic to do that 🤔
