### ISSUE TITLE
Feat: Close side buffers if they are the last

### ISSUE THREAD

**Issue by PrimaMateria** [shortcuts/no-neck-pain.nvim#62]
## Describe the problem

I am used to that nvim quits when I `<c-w>q ` my current window, which is the only one opened. Now, with the side buffers opened, it hangs on them.

## Describe the solution

The plugin checks if the only opened windows have the buff IDs which equal to side buffers, and if yes, it automatically closes them, which should result in closing the editor.

I can also try to help to work on the PR if I will have time.

**Comment by shortcuts** [comment]
Hey thanks! Taking a look at it

**Comment by shortcuts** [comment]
Found a pretty easy fix it seems, and actually it should've always been the case! Great catch thanks :)

I however wonder if this should be configurable :think:
