### ISSUE TITLE
Disables on horizontal split

### ISSUE THREAD

**Issue by cloudlena** [shortcuts/no-neck-pain.nvim#81]
## Description

The plugin shows the expected behavior when running `:vsplit` (i.e., it exits "centered" mode until I close the second vertical split).
However, I would not expect the plugin to exit "centered" mode, when `:split` is being run, as that doesn't require any additional horizontal space.

## Steps to reproduce

1. Run `:NoNeckPain`
1. Run `:split`
1. The plugin exits "centered" mode

## Expected behavior

I would expect the plugin to remain in "centered" mode until I run `:vsplit`.

## Environment

- Neovim: 0.8.x

**Comment by shortcuts** [comment]
Hey, thanks for the request! Definitely agree with the suggestion :)
