### ISSUE TITLE
When NoNeckPain mode toggled, running `:bdelete` also close the current window

### ISSUE THREAD

**Issue by noomly** [shortcuts/no-neck-pain.nvim#82]
First I'd like to thank you for writing this plugin, I've been wanting this kind of feature for so long!

## Description

After running `:NoNeckPain`, running `:bdelete` will close the current window even if there are multiple other opened buffers. This means that running `:bdelete` will effectively close Neovim if no other windows has been created, even if other buffers are opened.

## Steps to reproduce

1. Open Neovim
2. `:e buffer1`, `:e buffer2`
3. `:NoNeckPain`
4. `:bdelete`
5. Neovim closes even if there was still another buffer opened

## Expected behavior

Only buffer `buffer2` should have been closed.

## Environment

- Neovim: 0.8.1

**Comment by shortcuts** [comment]
Update: we quit nvim considering we closed the last window, while the event is a bufdelete. There should be a difference in how we handle those events.

**Comment by shortcuts** [comment]
Hey, please don't hesitate to try the fix :D

**Comment by noomly** [comment]
Hey just confirming the fix works for me. Thank you!
