### ISSUE TITLE
Allow enabling NoNeckPain per buffer

### ISSUE THREAD

**Issue by noomly** [shortcuts/no-neck-pain.nvim#83]
## Describe the problem

Currently, running `:NoNeckPain` will enable it for every opened and new buffers.

## Describe the solution

It would be nice to be able to choose whether to enable the NoNeckPain mode for every opened and new buffers or only for the current buffer. We could then be able to enable it on selected buffers rather than all of them by default. This would also, as a consequence, allow users to enable the plugin for specific filetypes using `autocmd`.

**Comment by shortcuts** [comment]
Hey, do you mean you'd like the plugin to automatically enables for specific files only?

**Comment by noomly** [comment]
Not exactly, I was more describing having a way to enable it manually per buffer. Say I'm looking at buffer A and I also have buffer B opened, if I run the command `:NoNeckPain enable-only-on-this-buffer` then NoNeckPain would be enabled for buffer A. Then if I switch to buffer B, NoNeckPain would be disabled, until I switch back to buffer A.

I'm not sure how feasible that would be but it'd be very useful in my use-case.

**Comment by shortcuts** [comment]
> Not exactly, I was more describing having a way to enable it manually per buffer. Say I'm looking at buffer A and I also have buffer B opened, if I run the command `:NoNeckPain enable-only-on-this-buffer` then NoNeckPain would be enabled for buffer A. Then if I switch to buffer B, NoNeckPain would be disabled, until I switch back to buffer A.
> 
> 
> 
> I'm not sure how feasible that would be but it'd be very useful in my use-case.

Ahhh that make sense, in that case it seems to perfectly suit the tab behavior on Neovim, not sure if we can abstract that at the buffer level
