### ISSUE TITLE
Side Buffers get disabled when switching tabs

### ISSUE THREAD

**Issue by AlphaKeks** [shortcuts/no-neck-pain.nvim#89]
## Description

When creating new tabs, or switching between existing ones, the side buffers disappear. They can be re-enabled manually but I don't think this behavior is intended.

## Steps to reproduce

1. Open nvim
2. run `:tabnew`
3. switch back to the original tab
4. the side buffers are gone

Note: if you close all extra tabs, they re-appear again.

## Expected behavior

They should not disappear.

## Environment

- Neovim: 0.8.1

![Screenshot at 18-35-17](https://user-images.githubusercontent.com/85143381/208969100-067bd1d6-4ebe-4e65-8e29-2a4f9d8ce29c.png)
![Screenshot at 18-35-25](https://user-images.githubusercontent.com/85143381/208969184-cfaadd48-cbae-42d2-88d9-be5dd276d7ae.png)

**Comment by shortcuts** [comment]
Hey, thanks for opening the issue! Indeed it's not expected, it seems to trigger the split logic 🤔

**Comment by shortcuts** [comment]
Did some tests and while it's the correct Neovim behavior to reset the window by creating a new tab, switching to an other tab should restore its state. 

Definitely needs to be handled
