### ISSUE TITLE
Content is shifted as diagnostics plugin shows a warning

### ISSUE THREAD

**Issue by 5Q1VM5bgef** [shortcuts/no-neck-pain.nvim#97]
## Description

The content of main buffer is shifted as diagnostics plugin shows a warning.

## Steps to reproduce

1. open nvim
1. run `:set signcolumn=auto`
1. make sure you're using at least one diagnostics plugin
1. make an error, so your diagnostics plugin shows a warning sign
1. the content of main buffer is shifted

## Expected behavior

Left empty buffer shrinks for the size of `signcolumn`. The content of main buffer stays still.

## Environment

- Neovim: 0.8.1
![unshifted](https://user-images.githubusercontent.com/111528540/209465636-5a7e6bd1-a7cb-4afd-bd1f-c4d619752eac.png)
![shifted](https://user-images.githubusercontent.com/111528540/209465660-97c40e5c-15e5-4328-ad27-97d55404a5d5.png)

**Comment by shortcuts** [comment]
Hey, Thanks for opening the issue!

Are you using the latest release or dev version of the plugin?

**Comment by 5Q1VM5bgef** [comment]
Hi,
I don't know. Where can I see it?

**Comment by 5Q1VM5bgef** [comment]
Whoops, accidentally closed the issue.

**Comment by shortcuts** [comment]
> Hi, I don't know. Where can I see it?

It depends how you install the package (see https://github.com/shortcuts/no-neck-pain.nvim#installation) if you don't provide a tag/version it will be `dev` (latest commit on main branch)

**Comment by shortcuts** [comment]
Just tried and can confirm it's reproducible, indeed we should consider the column width!

**Comment by 5Q1VM5bgef** [comment]
It's `dev` version, then.
I'm using packer and installing the package with a line:
`use("shortcuts/no-neck-pain.nvim")`

**Comment by shortcuts** [comment]
> It's `dev` version, then. I'm using packer and installing the package with a line: `use("shortcuts/no-neck-pain.nvim")`

Make sense, I'm working on a fix that prevent unwanted resize trigger, will see if it solves this too!

**Comment by shortcuts** [comment]
Hey, did some more testing in neovim without the plugin enabled, and it's the same behavior actually

**Comment by 5Q1VM5bgef** [comment]
Hi, yes, it's the same. It will be cool if the plugin will put an end to it.
It makes sense when plugin is not enabled. There's no space for `signcolumn` on the screen, so it shifts the content to be seen. Not so much when there's unused space and it can be used to lessen the distraction of refocusing the eyes.
It's not a zen mode plugin, so I could be wrong at opening an issue. Either way, it could be a separate option in setup options.
